### PR TITLE
Added support for pre-Honeycomb devices

### PR DESCRIPTION
**Pull request by consp1racy**

### CODE REVIEW

**Comment by chiuki** [comment]
Thanks for the pull request! 

After addressing the inline comments, please squash into a single commit:
http://eli.thegreenplace.net/2014/02/19/squashing-github-pull-requests-into-a-single-commit

**Comment by consp1racy** [comment]
Hi, I just finished. Thanks for teaching me this squashing, I never knew you could do this.

Apart from addressing the comments I also modified the layout to show two buttons at different locations for testing.

**Comment by chiuki** [comment]
If you want to make the different between partial and full more visible, you can change `res/values/styles.xml` to use `android:Theme.Light` instead of `android:Theme` so the text is dark.

**Comment by consp1racy** [comment]
It's not about visible changes. The problem was that even though the partial view's visibility was set to GONE and it's alpha to zero when expanded, it still somehow obscured the full view underneath, so you could not click anything in the full view.

Now if you can click the full view's button which is located at different position than partial view's button and get proper visible reaction (pressed state) it means the fix is working.

Otherwise I concur, it's not very eye-pleasing. And to answer the question the button itself does no-op.

**Comment by chiuki** [comment]
Okay, I see how you used the button to verify that your fix is working. But please don't leave it in the code. People who did not see this explanation will be confused. Also as a demo project I want the code to be as tight as possible.

**Comment by consp1racy** [comment]
Removed the button to avoid confusion.

**Comment by chiuki** [comment]
Thanks!

**Pull request merged**
